### ISSUE TITLE
Duration calculated at wrong line

### ISSUE THREAD

**Issue by mythgarr** [marques-work/p4-wrapper#1]
The command doesn't execute until cmd.CombinedOutput(), but the duration is calculated before that line. I've made a change locally and rebuilt the wrapper.
I was wondering why the verbose logs said a command took only 0ms but Go's logs said it took 25 minutes :)

**Comment by marques-work** [comment]
@mythgarr thanks for catching that. I’ll update the code, or if you want you can open a PR and I’ll merge it.

**Comment by marques-work** [comment]
Fixed as of 51ec3f0
